workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.clinicreminder"
      android_signing:
        - android_keystore
      xcode: latest
    scripts:
      - name: Set up environment
        script: |
          echo "Using JAVA_HOME=$JAVA_HOME"
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
